-- ============================================================
-- 006 — Table Comments
-- Depends on: 004 (all tables must exist)
-- Safe to run after any other chunk. Does not modify data.
-- ============================================================

comment on table public.sports is
  'Top-level sport categories. Uses generic Fanfolio names only (Pro Football, MMA, etc.).';

comment on table public.leagues is
  'League groupings within a sport. Uses generic Fanfolio names — no official league marks.';

comment on table public.generic_teams is
  'Generic team entities using city + sport suffix only. No mascots, logos, or official marks.
   Displays as "Kansas City Football Team", "Baltimore Football Team", etc.';

comment on table public.generic_player_roles is
  'Positional roles attached to teams. Describes roles (QB1, TE1) not real individuals.
   Display name: "Kansas City QB1 Coin", "Las Vegas RB1 Coin". No real player names.';

comment on table public.coach_roles is
  'Generic coaching archetype assets. No real coach names. Uses archetypes like
   "Offensive Mastermind", "Defensive Architect", "Hot Seat" as the display identity.';

comment on table public.assets is
  'Core tradeable asset registry. All public_name values use generic Fanfolio names.
   No real player/team/league branding in any user-visible column.';

comment on table public.asset_price_history is
  'Append-only simulated price history. source_type tracks whether the movement
   was seeded, triggered by a market event, or generated by the simulation engine.';

comment on table public.futures_markets is
  'Settlement definitions for future-type assets. No real odds, lines, or sportsbook data.
   Fanfolio futures are purely educational market simulations — LuckyCoin has no cash value.';

comment on table public.private_entity_aliases is
  'PRIVATE — backend/admin use only. Maps real-world entity names to generic Fanfolio names.
   Used by the server-side article entity adapter to resolve live news references
   into generic Fanfolio assets without ever exposing real names to the client app.
   No anon read policy — only service role / backend workers may access this table.
   The public client app must never query this table directly.';
