kind = "mobile"
previewPath = "/"
title = "Fanfolio"
version = "1.0.0"
id = "artifacts/fanfolio"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25121

[services.development]
run = "pnpm --filter @workspace/fanfolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fanfolio", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/fanfolio", "run", "serve" ]

[services.env]
PORT = "25121"
BASE_PATH = "/"
